In [309]:
import numpy as np
import time

def totalCost(N,A,k,connected):
    visited_array = connected[:]
    set_merge_visited = list(set(np.hstack(visited_array)))
    new_network = np.array([[0]*N]*N)
    for i in range(len(connected)):
        new_network[connected[i,1],connected[i,0]] = new_network[connected[i,0],connected[i,1]] = A[connected[i,0],connected[i,1]]
        A[connected[i,0],connected[i,1]] = A[connected[i,1],connected[i,0]] = 0
    new_network

    total = 0
    while True:
        min_cost = 999999
        for i in range(N):
            if i not in set_merge_visited:
                for j in range(len(set_merge_visited)):
                    if A[i,set_merge_visited[j]] > 0 and min_cost > A[i,set_merge_visited[j]]:
                        min_cost = A[i,set_merge_visited[j]]
                        new_i = i
                        new_j = set_merge_visited[j]
        new_network[new_i,new_j] = new_network[new_j,new_i] = A[new_i,new_j]
        total += A[new_i,new_j]
        A[new_i,new_j] = A[new_j,new_i] = 0
        set_merge_visited.append(new_i)
        set_merge_visited = list(set(np.array(set_merge_visited)))

        if len(set_merge_visited) == N:
            break
            
    return new_network, total

def main():
    N = int(input("Enter the number of buildings : "))
    print("Please input adjacency matrix, separated by space")
    data = [] 
    for i in range(0, N): 
        x = input("") 
        data.append(x) 
        b1 = data[i].split(" ") 
        data[i] = [int(a1) for a1 in b1] 
    k = int(input("Enter the number of buildings that have been connected : "))
    print("Please input the connected building")
    data2 = [] 
    for i in range(0, k): 
        x = input("") 
        data2.append(x) 
        b1 = data2[i].split(" ") 
        data2[i] = [int(a1) for a1 in b1] 
    start = time.time()
    result1, result2 = totalCost(N, np.array(data), k, np.array(data2))
    end = time.time()
    print("\n" + "===================================")
    print("\n" + "Total Cost : " + str(result2))
    print("\n" + "Connection with minimum cost: " + "\n" + str(result1))
    print("Time : " + str(round(end-start,5)) + " sec")

In [310]:
main()

Enter the number of buildings : 10
Please input adjacency matrix, separated by space
0 4 1 4 0 0 0 0 0 0
4 0 5 0 9 9 0 7 0 0
1 5 0 3 0 0 0 9 0 0
4 0 3 0 0 0 0 10 0 18
0 9 0 0 0 2 4 0 6 0
0 9 0 0 2 0 2 8 0 0
0 0 0 0 4 2 0 9 3 9
0 7 9 10 0 8 9 0 0 8
0 0 0 0 6 0 3 0 0 9
0 0 0 18 0 0 9 8 9 0
Enter the number of buildings that have been connected : 2
Please input the connected building
0 1
0 2


Total Cost : 33

Connection with minimum cost: 
[[0 4 1 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 7 0 0]
 [1 0 0 3 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 2 0 2 8 0 0]
 [0 0 0 0 0 2 0 0 3 0]
 [0 7 0 0 0 8 0 0 0 8]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 8 0 0]]
Time : 0.0 sec


In [312]:
main()

Enter the number of buildings : 3
Please input adjacency matrix, separated by space
0 981 600
981 0 170
600 170 0
Enter the number of buildings that have been connected : 1
Please input the connected building
0 1


Total Cost : 170

Connection with minimum cost: 
[[  0 981   0]
 [981   0 170]
 [  0 170   0]]
Time : 0.0 sec
