In [1]:
import time
import numpy as np

def mmult(a,b):
    rowa = len(a)
    rowb = len(b)
    colb = len(b[0])
    r = [[0 for i in range(colb)] for j in range(rowa)]
    for i in range(rowa):
        for j in range(colb):
            for k in range(rowb):
                r[i][j] = (r[i][j] + (a[i][k]) * (b[k][j])) % 32767
    return(r)

def PowerSeq(n,k,X):
    lenx = len(X)

    A = np.array([[0 for i in range(lenx * 2)] for j in range(lenx * 2)])
    A[:lenx,:lenx] = X

    i,j = 0,0
    while True:
        if i == lenx or j == lenx*2:
            break
        A[i,lenx+j] = 1
        A[lenx+i,lenx+j] = 1
        i,j = i+1, j+1

    r = [[0 for x in range(lenx * 2)] for y in range(lenx * 2)]
    r[lenx-1][lenx-1] = 1
    for i in (range(lenx * 2)):
        r[i][i] = 1

    B = A[:,lenx:]
    k = k // 2
    modk = k % 2
    while True:
        A = np.array(mmult(A,A)) % 32767
        if modk == 1:
            r = np.array(mmult(r,A)) % 32767
        modk = k % 2
        k = k // 2
        if k == 0:
            r = np.array(mmult(r,A)) % 32767
            result = np.array(mmult(r,B)) % 32767 - B
            break

    return(result[:n,:])

def main():
    n = int(input("Enter the size of matrix : "))
    k = int(input("Enter the sequence limit : "))
    print("Please input your array")
    data = [] 
    for i in range(0, n): 
        x = input("") 
        data.append(x) 
        b = data[i].split(" ") 
        data[i] = [int(a) for a in b] 
    print("Your array is: ", data)
    start = time.time()
    result = PowerSeq(n,k,data)
    end = time.time()
    print("\n" + "===================================")
    print("\n" + "Output : " + "\n" + str(result))
    print("\n", "Time : " + str(round(end-start,5)) + " sec")

In [2]:
main()

Enter the size of matrix : 3
Enter the sequence limit : 4
Please input your array
1 2 3
4 5 6
7 8 9
Your array is:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Output : 
[[ 8059  9902 11745]
 [18250 22424 26598]
 [28441  2179  8684]]

 Time : 0.03325 sec


In [3]:
main()

Enter the size of matrix : 3
Enter the sequence limit : 1000
Please input your array
1 2 3
4 5 6
7 8 9
Your array is:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Output : 
[[20104  6146 24955]
 [20160 27167  1407]
 [20216 15421 10626]]

 Time : 0.0039 sec


In [4]:
main()

Enter the size of matrix : 3
Enter the sequence limit : 1000000
Please input your array
1 2 3
4 5 6
7 8 9
Your array is:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Output : 
[[21196 32298 10633]
 [12922  3234 26313]
 [ 4648  6937  9226]]

 Time : 0.00795 sec
